import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:weather_app/data/models/forecast_model.dart';
import 'package:weather_app/data/models/weather_current_model.dart';
import 'package:weather_app/data/models/weather_location_model.dart';
import 'package:weather_app/data/models/weatheralert_list_model.dart';
import 'package:weather_app/domain/entity/weather_response_entity.dart';
// required: associates our `weather_response_model.dart` with the code generated by Freezed
part 'weather_response_model.freezed.dart';
// optional: Since our weather_response_model class is serializable, we must add this line.
// But if weather_response_model was not serializable, we could skip it.
part 'weather_response_model.g.dart';

@freezed
abstract class WeatherResponseModel
    with _$WeatherResponseModel
    implements WeatherResponseEntity {
  const factory WeatherResponseModel({
    required WeatherLocationModel location,
    required WeatherCurrentModel current,
    WeatherAlertListModel? alerts,
    required ForecastModel forecast,
  }) = _WeatherResponseModel;

  factory WeatherResponseModel.fromJson(Map<String, Object?> json) =>
      _$WeatherResponseModelFromJson(json);
}
