import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:weather_app/data/models/weather_alert_model.dart';
// required: associates our `weatheralert_list_model.dart` with the code generated by Freezed
part 'weatheralert_list_model.freezed.dart';
// optional: Since our weatheralert_list_model class is serializable, we must add this line.
// But if weatheralert_list_model was not serializable, we could skip it.
part 'weatheralert_list_model.g.dart';

@freezed
abstract class WeatherAlertListModel with _$WeatherAlertListModel {
  const factory WeatherAlertListModel({
    @Default([]) List<WeatherAlertModel> alert,
  }) = _WeatherAlertListModel;

  factory WeatherAlertListModel.fromJson(Map<String, dynamic> json) =>
      _$WeatherAlertListModelFromJson(json);
}
